### ISSUE TITLE
`make test` broken in latest master

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#139]
@kushaldas reported, and @conorsch confirmed, the following errors with `make test` in https://github.com/freedomofpress/securedrop-workstation/issues/127#issuecomment-417749100:

<details>
<summary>Detailed output</summary>

```
$ make test
python -m unittest discover tests
EF
.
.
.
.
./bin/cat: /usr/local/bin/do-not-open-here: No such file or directory
E/bin/cat: /usr/local/bin/move-to-svs: No such file or directory
E/bin/cat: /usr/local/bin/sd-process-display: No such file or directory
E/bin/cat: /usr/local/bin/sd-process-download: No such file or directory
E/bin/cat: /usr/local/bin/sd-process-feedback: No such file or directory
E...........
.
.
.
.
======================================================================
ERROR: test_dispvm (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_dispvm
Traceback (most recent call last):
File "/usr/lib64/python2.7/unittest/loader.py", line 254, in _find_tests
module = self._get_module_from_name(name)
File "/usr/lib64/python2.7/unittest/loader.py", line 232, in _get_module_from_name
__import__(name)
File "/home/kdas/securedrop-workstation/tests/test_dispvm.py", line 9, in <module>
import qubes.tests
ImportError: No module named qubes.tests


======================================================================
ERROR: test_do_not_open_here (test_journalist_vm.SD_Journalist_Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/kdas/securedrop-workstation/tests/test_journalist_vm.py", line 21, in test_do_not_open_here
"sd-journalist/do-not-open-here")
File "/home/kdas/securedrop-workstation/tests/base.py", line 55, in assertFilesMatch
remote_content = self._get_file_contents(remote_path)
File "/home/kdas/securedrop-workstation/tests/base.py", line 51, in _get_file_contents
"/bin/cat {}".format(path)])
File "/usr/lib64/python2.7/subprocess.py", line 219, in check_output
raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['qvm-run', '-p', 'sd-journalist', '/bin/cat /usr/local/bin/do-not-open-here']' returned non-zero exit status 1

======================================================================
ERROR: test_move_to_svs (test_journalist_vm.SD_Journalist_Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/kdas/securedrop-workstation/tests/test_journalist_vm.py", line 13, in test_move_to_svs
"sd-journalist/move-to-svs")
File "/home/kdas/securedrop-workstation/tests/base.py", line 55, in assertFilesMatch
remote_content = self._get_file_contents(remote_path)
File "/home/kdas/securedrop-workstation/tests/base.py", line 51, in _get_file_contents
"/bin/cat {}".format(path)])
File "/usr/lib64/python2.7/subprocess.py", line 219, in check_output
raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['qvm-run', '-p', 'sd-journalist', '/bin/cat /usr/local/bin/move-to-svs']' returned non-zero exit status 1

======================================================================
ERROR: test_sd_process_display (test_journalist_vm.SD_Journalist_Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/kdas/securedrop-workstation/tests/test_journalist_vm.py", line 29, in test_sd_process_display
"sd-journalist/sd-process-display")
File "/home/kdas/securedrop-workstation/tests/base.py", line 55, in assertFilesMatch
remote_content = self._get_file_contents(remote_path)
File "/home/kdas/securedrop-workstation/tests/base.py", line 51, in _get_file_contents
"/bin/cat {}".format(path)])
File "/usr/lib64/python2.7/subprocess.py", line 219, in check_output
raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['qvm-run', '-p', 'sd-journalist', '/bin/cat /usr/local/bin/sd-process-display']' returned non-zero exit status 1

======================================================================
ERROR: test_sd_process_download (test_journalist_vm.SD_Journalist_Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/kdas/securedrop-workstation/tests/test_journalist_vm.py", line 17, in test_sd_process_download
"sd-journalist/sd-process-download")
File "/home/kdas/securedrop-workstation/tests/base.py", line 55, in assertFilesMatch
remote_content = self._get_file_contents(remote_path)
File "/home/kdas/securedrop-workstation/tests/base.py", line 51, in _get_file_contents
"/bin/cat {}".format(path)])
File "/usr/lib64/python2.7/subprocess.py", line 219, in check_output
raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['qvm-run', '-p', 'sd-journalist', '/bin/cat /usr/local/bin/sd-process-download']' returned non-zero exit status 1

======================================================================
ERROR: test_sd_process_feedback (test_journalist_vm.SD_Journalist_Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/kdas/securedrop-workstation/tests/test_journalist_vm.py", line 25, in test_sd_process_feedback
"sd-journalist/sd-process-feedback")
File "/home/kdas/securedrop-workstation/tests/base.py", line 55, in assertFilesMatch
remote_content = self._get_file_contents(remote_path)
File "/home/kdas/securedrop-workstation/tests/base.py", line 51, in _get_file_contents
"/bin/cat {}".format(path)])
File "/usr/lib64/python2.7/subprocess.py", line 219, in check_output
raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['qvm-run', '-p', 'sd-journalist', '/bin/cat /usr/local/bin/sd-process-feedback']' returned non-zero exit status 1

======================================================================
FAIL: test_accept_sd_xfer_extracted_file (test_sd_whonix.SD_Whonix_Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/kdas/securedrop-workstation/tests/test_sd_whonix.py", line 20, in test_accept_sd_xfer_extracted_file
self.assertFileHasLine("/usr/local/etc/torrc.d/50_user.conf", line)
File "/home/kdas/securedrop-workstation/tests/base.py", line 72, in assertFileHasLine
raise AssertionError(msg)
AssertionError: File /usr/local/etc/torrc.d/50_user.conf does not contain expected line HidServAuth avgfxawdn6c3coe3.onion Il8Xas7uf6rjtc0LxYwhrx

----------------------------------------------------------------------
Ran 27 tests in 78.106s

FAILED (failures=1, errors=6)
Makefile:100: recipe for target 'test' failed
make: *** [test] Error 1
```
</details>

<br>

@conorsch also notes:

>  I'll note also that during salt provisioning runs against e.g. sd-journalist, a temporary management VM spins up, i.e. disp-mgmt-sd-journalist. That should only happen when the target vm is a TemplateVM, but sd-journalist VM is an AppVM. (See #131 for using TemplateVMs across the board.) @joshuathayer has not yet been able to reproduce this failure, so I suspect there's a bit of dev env drift somewhere that we need to investigate.

**Comment by conorsch** [comment]
During a brief debugging session just now, @joshuathayer pointed me to `dom0:/var/log/qubes/mgmt-sd-journalist.log`, which showed a stack trace on salt calls during. Snippet:

[placeholder for traceback]

**Comment by conorsch** [comment]
Note that we cannot install this package via salt in the VM, because the package is required to run salt in the VM. :slightly_smiling_face: _face: As a stopgap, we should be able to leverage the salt config targeting dom0 to run an ad-hoc `apt-get` command to force the package presence that way. Will test that locally before opening a slim PR.

**Comment by redshiftzero** [comment]
Done via #143

**Comment by kushaldas** [comment]
My `sd-whonix-template` is missing the same Python package today.
