### ISSUE TITLE
T490 fails to start sys-net after applying workstation updates

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-workstation#741]
On a Thinkpad T490 (development workstation environment), running the Preflight Updater produces errors (sometimes a flood of errors) and prevents sys-net from rebooting, and subsequent attempts to restart sys-net are met with the same. 

Rebooting the computer resolves the issue. 

**Additional relevant info:**
 
- PCI stuff: before setting up the Workstation, I had to enable `no-strict-reset=True` for my Ethernet controller as per [these instructions](https://www.qubes-os.org/doc/pci-troubleshooting/#domain--has-failed-to-start-internal-error-unable-to-reset-pci-device--no-flr-pm-reset-or-bus-reset-available), and I used the sys-net settings GUI to accomplish this.
- I think the `sys-usb` issue pictured in the notifications is a red herring and just had to do with memory issues
- Using the Qubes GUI updater does not seem to cause these issues, but then again, qubes GUI updater isn't applying updates for sys-net's template so maybe that is neither here nor there
- Force-stopping and restarting sys-net (`qvm-run sys-net "sudo halt"`) does not cause any issues 

Attached are screenshots of the error (I'll put log snippets from `journalctl`, `/var/log/qubes/qubes.log`, and `/var/log/libvirtl/libxl-log` in a comment below to keep this readable and I can grab other logs as need be).

@creviera mentioned encountering a similar-sounding issue, also on a T490. 

**First error:**

![sys-net-error](https://user-images.githubusercontent.com/22777700/144455140-ca72ea74-d27b-4d88-94e8-75f7a7c1a21d.png)

**Second set of errors:**

![updates-reboot-error2](https://user-images.githubusercontent.com/22777700/144455136-73266488-3b74-4eb1-9557-732f5456cf30.png)

**Definitely having a sad:**

![reboot-error-3](https://user-images.githubusercontent.com/22777700/144455134-d83f66d5-7bb8-44a5-99f0-5e821118bafd.png)

**Comment by rocodes** [comment]
**journalctl:**
```
Dec 02 10:12:52 dom0 dmeventd[775]: No longer monitoring thin pool qubes_dom0-pool00-tpool.
Dec 02 10:12:52 dom0 lvm[775]: Monitoring thin pool qubes_dom0-pool00-tpool.
Dec 02 10:12:53 dom0 libvirtd[2190]: 2021-12-02 15:12:53.408+0000: 2234: error : virPCIGetHeaderType:3129 : internal error: Unknown PCI header type '127'
Dec 02 10:12:53 dom0 qubesd[2172]: Start failed: internal error: Unknown PCI header type '127'
Dec 02 10:12:53 dom0 dmeventd[775]: No longer monitoring thin pool qubes_dom0-pool00-tpool.
Dec 02 10:12:55 dom0 lvm[775]: Monitoring thin pool qubes_dom0-pool00-tpool.
Dec 02 10:12:55 dom0 dmeventd[775]: No longer monitoring thin pool qubes_dom0-pool00-tpool.
Dec 02 10:12:56 dom0 lvm[775]: Monitoring thin pool qubes_dom0-pool00-tpool.
Dec 02 10:12:56 dom0 qrexec[18776]: qubes.NotifyUpdates: sd-log -> dom0: allowed to dom0
Dec 02 10:12:56 dom0 qmemman.daemon.reqhandler[2156]: client disconnected, resuming membalance
Dec 02 10:12:56 dom0 qmemman.daemon.algo[2156]: balance_when_enough_memory(xen_free_memory=571004038, total_mem_pref=12531428966.400002, total_available_memory=24127553072.600002)
Dec 02 10:12:56 dom0 qmemman.daemon.algo[2156]: left_memory=12283022984 acceptors_count=6
Dec 02 10:12:56 dom0 qmemman.systemstate[2156]: stat: dom '25' act=3591164130 pref=542895308.8000001 last_target=3591164130
Dec 02 10:12:56 dom0 qmemman.systemstate[2156]: stat: dom '170' act=3145874728 pref=391356825.6 last_target=3145874728
Dec 02 10:12:56 dom0 qmemman.systemstate[2156]: stat: dom '15' act=3450906462 pref=500414054.40000004 last_target=3450906462
Dec 02 10:12:56 dom0 qmemman.systemstate[2156]: stat: dom '16' act=6250040392 pref=4712059289.6 last_target=6250040392
Dec 02 10:12:56 dom0 qmemman.systemstate[2156]: stat: dom '49' act=4873338991 pref=988820684.8000001 last_target=4873338991
Dec 02 10:12:56 dom0 qmemman.systemstate[2156]: stat: dom '0' act=4236199264 pref=2053830656.0 last_target=4236199264
Dec 02 10:12:56 dom0 qmemman.systemstate[2156]: stat: dom '168' act=3229221199 pref=417954201.6 last_target=3229221199
Dec 02 10:12:56 dom0 qmemman.systemstate[2156]: stat: dom '166' act=3161494316 pref=429312000.0 last_target=3161494316
Dec 02 10:12:56 dom0 qmemman.systemstate[2156]: stat: dom '30' act=4149738519 pref=2494785945.6 last_target=4149738519
Dec 02 10:12:56 dom0 qmemman.systemstate[2156]: stat: xenfree=623432838 memset_reqs=[('166', 3299760989), ('49', 4934890379), ('15', 3507552328), ('30', 4194304000), ('16', 6291456000), ('25', 3631701156), ('168', 3266568528), ('170', 3188839348), ('0', 4294967296)]
Dec 02 10:12:56 dom0 qmemman.systemstate[2156]: mem-set domain 166 to 3299760989
Dec 02 10:12:56 dom0 qmemman.systemstate[2156]: mem-set domain 49 to 4934890379
Dec 02 10:12:56 dom0 qmemman.systemstate[2156]: mem-set domain 15 to 3507552328
Dec 02 10:12:56 dom0 qmemman.systemstate[2156]: mem-set domain 30 to 4194304000
Dec 02 10:12:56 dom0 qmemman.systemstate[2156]: mem-set domain 16 to 6291456000
Dec 02 10:12:56 dom0 qmemman.systemstate[2156]: mem-set domain 25 to 3631701156
Dec 02 10:12:56 dom0 qmemman.systemstate[2156]: mem-set domain 168 to 3266568528
Dec 02 10:12:56 dom0 qmemman.systemstate[2156]: mem-set domain 170 to 3188839348
Dec 02 10:12:56 dom0 qmemman.systemstate[2156]: mem-set domain 0 to 4294967296
Dec 02 10:12:56 dom0 qmemman.daemon.algo[2156]: balance_when_enough_memory(xen_free_memory=34226075, total_mem_pref=12524597248.000002, total_available_memory=24119668851.000004)
Dec 02 10:12:56 dom0 qmemman.daemon.algo[2156]: left_memory=12286915216 acceptors_count=6
Dec 02 10:12:56 dom0 qmemman.daemon.algo[2156]: balance_when_enough_memory(xen_free_memory=33953974, total_mem_pref=12524597248.000002, total_available_memory=24119396750.000004)
Dec 02 10:12:56 dom0 qmemman.daemon.algo[2156]: left_memory=12286714227 acceptors_count=6
Dec 02 10:13:26 dom0 qmemman.daemon.algo[2156]: balance_when_enough_memory(xen_free_memory=52600010, total_mem_pref=12566466150.400002, total_available_memory=24096173883.600002)
```


**/var/log/qubes/qubes.log**:  
```
2021-12-02 09:54:46,232 Creating directory: /var/lib/qubes/appvms/disp-mgmt-whonix-gw-16
2021-12-02 09:54:46,258 Creating icon symlink: /var/lib/qubes/appvms/disp-mgmt-whonix-gw-16/icon.png -> /usr/share/icons/hicolor/128x128/devices/appvm-black.png
2021-12-02 09:54:49,405 Starting disp-mgmt-whonix-gw-16
2021-12-02 09:54:52,897 Setting Qubes DB info for the VM
2021-12-02 09:54:52,898 Starting Qubes DB
2021-12-02 09:54:52,986 Activating the disp-mgmt-whonix-gw-16 VM
2021-12-02 09:55:08,134 Starting whonix-gw-16
2021-12-02 09:55:11,863 Setting Qubes DB info for the VM
2021-12-02 09:55:11,863 Starting Qubes DB
2021-12-02 09:55:11,978 Activating the whonix-gw-16 VM
2021-12-02 09:55:17,315 Starting sys-whonix
2021-12-02 09:55:22,118 Setting Qubes DB info for the VM
2021-12-02 09:55:22,118 Starting Qubes DB
2021-12-02 09:55:22,287 Activating the sys-whonix VM
2021-12-02 09:56:13,388 permission denied for call b'admin.vm.List'+b'' (b'dom0' → b'disp-mgmt-whonix-gw-16') with payload of 0 bytes
2021-12-02 09:56:13,414 permission denied for call b'admin.vm.volume.Info'+b'volatile' (b'dom0' → b'disp-mgmt-whonix-gw-16') with payload of 0 bytes
2021-12-02 09:56:13,574 Removing volume root: qubes_dom0/vm-disp-mgmt-whonix-gw-16-root
2021-12-02 09:56:13,574 Removing volume volatile: qubes_dom0/vm-disp-mgmt-whonix-gw-16-volatile
2021-12-02 09:56:13,575 Removing volume kernel: 5.4.156-1.fc25
2021-12-02 09:56:13,575 Removing volume private: qubes_dom0/vm-disp-mgmt-whonix-gw-16-private
2021-12-02 09:56:15,131 Creating directory: /var/lib/qubes/appvms/disp-mgmt-fedora-34
2021-12-02 09:56:15,165 Creating icon symlink: /var/lib/qubes/appvms/disp-mgmt-fedora-34/icon.png -> /usr/share/icons/hicolor/128x128/devices/appvm-black.png
2021-12-02 09:56:18,787 Starting disp-mgmt-fedora-34
2021-12-02 09:56:22,235 Setting Qubes DB info for the VM
2021-12-02 09:56:22,235 Starting Qubes DB
2021-12-02 09:56:22,353 Activating the disp-mgmt-fedora-34 VM
2021-12-02 09:56:38,252 Starting fedora-34
2021-12-02 09:56:42,277 Setting Qubes DB info for the VM
2021-12-02 09:56:42,277 Starting Qubes DB
2021-12-02 09:56:42,383 Activating the fedora-34 VM
2021-12-02 09:57:55,055 permission denied for call b'admin.vm.List'+b'' (b'dom0' → b'disp-mgmt-fedora-34') with payload of 0 bytes
2021-12-02 09:57:55,106 permission denied for call b'admin.vm.volume.Info'+b'volatile' (b'dom0' → b'disp-mgmt-fedora-34') with payload of 0 bytes
2021-12-02 09:57:55,441 Removing volume root: qubes_dom0/vm-disp-mgmt-fedora-34-root
2021-12-02 09:57:55,441 Removing volume volatile: qubes_dom0/vm-disp-mgmt-fedora-34-volatile
2021-12-02 09:57:55,441 Removing volume kernel: 5.4.156-1.fc25
2021-12-02 09:57:55,442 Removing volume private: qubes_dom0/vm-disp-mgmt-fedora-34-private
2021-12-02 09:57:57,240 Creating directory: /var/lib/qubes/appvms/disp-mgmt-sd-large-buster-templ
2021-12-02 09:57:57,282 Creating icon symlink: /var/lib/qubes/appvms/disp-mgmt-sd-large-buster-templ/icon.png -> /usr/share/icons/hicolor/128x128/devices/appvm-black.png
2021-12-02 09:58:01,653 Starting disp-mgmt-sd-large-buster-templ
2021-12-02 09:58:05,151 Setting Qubes DB info for the VM
2021-12-02 09:58:05,152 Starting Qubes DB
2021-12-02 09:58:05,259 Activating the disp-mgmt-sd-large-buster-templ VM
2021-12-02 09:58:20,344 Starting sd-large-buster-template
2021-12-02 09:58:25,082 Setting Qubes DB info for the VM
2021-12-02 09:58:25,083 Starting Qubes DB
2021-12-02 09:58:25,180 Activating the sd-large-buster-template VM
2021-12-02 09:59:47,752 permission denied for call b'admin.vm.device.block.Available'+b'' (b'dom0' → b'disp-mgmt-sd-large-buster-templ') with payload of 0 bytes
2021-12-02 09:59:47,848 permission denied for call b'admin.vm.List'+b'' (b'dom0' → b'disp-mgmt-sd-large-buster-templ') with payload of 0 bytes
2021-12-02 09:59:47,868 permission denied for call b'admin.vm.volume.Info'+b'volatile' (b'dom0' → b'disp-mgmt-sd-large-buster-templ') with payload of 0 bytes
2021-12-02 09:59:48,130 Removing volume root: qubes_dom0/vm-disp-mgmt-sd-large-buster-templ-root
2021-12-02 09:59:48,130 Removing volume volatile: qubes_dom0/vm-disp-mgmt-sd-large-buster-templ-volatile
2021-12-02 09:59:48,131 Removing volume kernel: 5.4.156-1.fc25
2021-12-02 09:59:48,131 Removing volume private: qubes_dom0/vm-disp-mgmt-sd-large-buster-templ-private
2021-12-02 09:59:49,807 Creating directory: /var/lib/qubes/appvms/disp-mgmt-sd-small-buster-templ
2021-12-02 09:59:49,841 Creating icon symlink: /var/lib/qubes/appvms/disp-mgmt-sd-small-buster-templ/icon.png -> /usr/share/icons/hicolor/128x128/devices/appvm-black.png
2021-12-02 09:59:53,451 Starting disp-mgmt-sd-small-buster-templ
2021-12-02 09:59:57,158 Setting Qubes DB info for the VM
2021-12-02 09:59:57,159 Starting Qubes DB
2021-12-02 09:59:57,251 Activating the disp-mgmt-sd-small-buster-templ VM
2021-12-02 10:01:03,587 permission denied for call b'admin.vm.List'+b'' (b'dom0' → b'disp-mgmt-sd-small-buster-templ') with payload of 0 bytes
2021-12-02 10:01:03,605 permission denied for call b'admin.vm.volume.Info'+b'volatile' (b'dom0' → b'disp-mgmt-sd-small-buster-templ') with payload of 0 bytes
2021-12-02 10:01:03,836 Removing volume root: qubes_dom0/vm-disp-mgmt-sd-small-buster-templ-root
2021-12-02 10:01:03,837 Removing volume volatile: qubes_dom0/vm-disp-mgmt-sd-small-buster-templ-volatile
2021-12-02 10:01:03,837 Removing volume kernel: 5.4.156-1.fc25
2021-12-02 10:01:03,837 Removing volume private: qubes_dom0/vm-disp-mgmt-sd-small-buster-templ-private
2021-12-02 10:01:21,752 socket.send() raised exception.
2021-12-02 10:02:06,503 Starting sys-net
2021-12-02 10:05:49,914 Start failed: An error occurred, but the cause is unknown
2021-12-02 10:06:02,946 Task exception was never retrieved
future: <Task finished coro=<ThinVolume.stop() done, defined at /usr/lib/python3.5/site-packages/qubes/storage/__init__.py:171> exception=StoragePoolException('  Logical volume qubes_dom0/vm-sys-net-root-snap in use.',)>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/site-packages/qubes/storage/__init__.py", line 175, in wrapper
    return (yield from method(self, *args, **kwargs))
  File "/usr/lib/python3.5/site-packages/qubes/storage/lvm.py", line 664, in stop
    yield from qubes_lvm_coro(cmd, self.log)
  File "/usr/lib/python3.5/site-packages/qubes/storage/lvm.py", line 805, in qubes_lvm_coro
    return _process_lvm_output(p.returncode, out, err, log)
  File "/usr/lib/python3.5/site-packages/qubes/storage/lvm.py", line 771, in _process_lvm_output
    raise qubes.storage.StoragePoolException(err)
qubes.storage.StoragePoolException:   Logical volume qubes_dom0/vm-sys-net-root-snap in use.
2021-12-02 10:06:03,076 Starting sys-firewall
2021-12-02 10:06:03,079 Starting sys-net
2021-12-02 10:06:13,308 Start failed:   Logical Volume "vm-sys-net-volatile" already exists in volume group "qubes_dom0"
2021-12-02 10:06:13,311 Start failed:   Logical Volume "vm-sys-net-volatile" already exists in volume group "qubes_dom0"
2021-12-02 10:06:13,550 Task exception was never retrieved
future: <Task finished coro=<ThinVolume.start() done, defined at /usr/lib/python3.5/site-packages/qubes/storage/__init__.py:171> exception=StoragePoolException('  Logical Volume "vm-sys-net-root-snap" already exists in volume group "qubes_dom0"',)>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/site-packages/qubes/storage/__init__.py", line 175, in wrapper
    return (yield from method(self, *args, **kwargs))
  File "/usr/lib/python3.5/site-packages/qubes/storage/lvm.py", line 649, in start
    yield from self._snapshot()
  File "/usr/lib/python3.5/site-packages/qubes/storage/lvm.py", line 640, in _snapshot
    yield from qubes_lvm_coro(cmd, self.log)
  File "/usr/lib/python3.5/site-packages/qubes/storage/lvm.py", line 805, in qubes_lvm_coro
    return _process_lvm_output(p.returncode, out, err, log)
  File "/usr/lib/python3.5/site-packages/qubes/storage/lvm.py", line 771, in _process_lvm_output
    raise qubes.storage.StoragePoolException(err)
qubes.storage.StoragePoolException:   Logical Volume "vm-sys-net-root-snap" already exists in volume group "qubes_dom0"
2021-12-02 10:06:13,664 Starting sys-whonix
2021-12-02 10:06:13,667 Starting sys-firewall
2021-12-02 10:06:13,672 Starting sys-net
2021-12-02 10:06:23,647 Start failed:   Logical Volume "vm-sys-net-volatile" already exists in volume group "qubes_dom0"
2021-12-02 10:06:23,649 Start failed:   Logical Volume "vm-sys-net-volatile" already exists in volume group "qubes_dom0"
2021-12-02 10:06:23,651 Start failed:   Logical Volume "vm-sys-net-volatile" already exists in volume group "qubes_dom0"
2021-12-02 10:06:23,895 Task exception was never retrieved
future: <Task finished coro=<ThinVolume.start() done, defined at /usr/lib/python3.5/site-packages/qubes/storage/__init__.py:171> exception=StoragePoolException('  Logical Volume "vm-sys-net-root-snap" already exists in volume group "qubes_dom0"',)>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/site-packages/qubes/storage/__init__.py", line 175, in wrapper
    return (yield from method(self, *args, **kwargs))
  File "/usr/lib/python3.5/site-packages/qubes/storage/lvm.py", line 649, in start
    yield from self._snapshot()
  File "/usr/lib/python3.5/site-packages/qubes/storage/lvm.py", line 640, in _snapshot
    yield from qubes_lvm_coro(cmd, self.log)
  File "/usr/lib/python3.5/site-packages/qubes/storage/lvm.py", line 805, in qubes_lvm_coro
    return _process_lvm_output(p.returncode, out, err, log)
  File "/usr/lib/python3.5/site-packages/qubes/storage/lvm.py", line 771, in _process_lvm_output
    raise qubes.storage.StoragePoolException(err)
qubes.storage.StoragePoolException:   Logical Volume "vm-sys-net-root-snap" already exists in volume group "qubes_dom0"
2021-12-02 10:06:24,010 Starting sys-usb
2021-12-02 10:06:45,628 Start failed: internal error: Unable to reset PCI device 0000:00:14.0: internal error: libxenlight failed to create new domain 'sys-usb'
2021-12-02 10:06:49,425 Starting sd-log
2021-12-02 10:06:52,513 Setting Qubes DB info for the VM
2021-12-02 10:06:52,513 Starting Qubes DB
2021-12-02 10:06:52,597 Activating the sd-log VM
2021-12-02 10:07:05,116 Starting sd-gpg
2021-12-02 10:07:09,334 Setting Qubes DB info for the VM
2021-12-02 10:07:09,334 Starting Qubes DB
2021-12-02 10:07:09,451 Activating the sd-gpg VM
2021-12-02 10:07:22,899 Starting sd-whonix
2021-12-02 10:07:22,909 Starting sys-firewall
2021-12-02 10:07:22,918 Starting sys-net
2021-12-02 10:07:24,526 Start failed: internal error: Unknown PCI header type '127'
2021-12-02 10:07:28,459 Start failed: internal error: Unknown PCI header type '127'
2021-12-02 10:07:28,462 Start failed: internal error: Unknown PCI header type '127'
2021-12-02 10:07:29,064 Starting sd-proxy
2021-12-02 10:07:29,069 Starting sd-whonix
2021-12-02 10:07:29,072 Starting sys-firewall
2021-12-02 10:07:29,076 Starting sys-net
2021-12-02 10:07:30,372 Start failed: internal error: Unknown PCI header type '127'
2021-12-02 10:07:34,198 Start failed: internal error: Unknown PCI header type '127'
2021-12-02 10:07:34,202 Start failed: internal error: Unknown PCI header type '127'
2021-12-02 10:07:34,202 Start failed: internal error: Unknown PCI header type '127'
2021-12-02 10:07:34,732 Starting sd-app
2021-12-02 10:07:38,611 Setting Qubes DB info for the VM
2021-12-02 10:07:38,611 Starting Qubes DB
2021-12-02 10:07:38,680 Activating the sd-app VM
2021-12-02 10:12:52,149 Starting sys-net
2021-12-02 10:12:53,409 Start failed: internal error: Unknown PCI header type '127'
```

**/var/log/libvirt/libxl/libxl-driver.log** (This is the same time period, despite the fact that it's timestamped in UTC):

```2021-12-02 14:54:22.557+0000: libxl: libxl.c:1669:devices_destroy_cb: libxl__devices_destroy failed for 136
2021-12-02 15:01:16.373+0000: libxl: libxl_device.c:1099:device_backend_callback: unable to remove device with path /local/domain/15/backend/vif/151/0
2021-12-02 15:01:16.402+0000: libxl: libxl.c:1669:devices_destroy_cb: libxl__devices_destroy failed for 151
2021-12-02 15:01:23.648+0000: libxl: libxl_device.c:1099:device_backend_callback: unable to remove device with path /local/domain/71/backend/vif/79/0
2021-12-02 15:01:23.675+0000: libxl: libxl.c:1669:devices_destroy_cb: libxl__devices_destroy failed for 79
2021-12-02 15:01:43.707+0000: libxl: libxl_pci.c:1202:libxl__device_pci_reset: The kernel doesn't support reset from sysfs for PCI device 0000:00:14.0
2021-12-02 15:01:52.555+0000: libxl: libxl_device.c:1099:device_backend_callback: unable to remove device with path /local/domain/71/backend/vif/156/0
2021-12-02 15:01:52.577+0000: libxl: libxl.c:1669:devices_destroy_cb: libxl__devices_destroy failed for 156
2021-12-02 15:02:01.258+0000: libxl: libxl_device.c:983:libxl__initiate_device_generic_remove: backend /local/domain/71/backend/vif/49/0 already removed, cleanup frontend only
2021-12-02 15:02:01.309+0000: libxl: libxl_device.c:983:libxl__initiate_device_generic_remove: backend /local/domain/71/backend/vif/130/0 already removed, cleanup frontend only
2021-12-02 15:02:01.348+0000: libxl: libxl_device.c:983:libxl__initiate_device_generic_remove: backend /local/domain/71/backend/vif/128/0 already removed, cleanup frontend only
2021-12-02 15:02:01.501+0000: libxl: libxl_pci.c:1202:libxl__device_pci_reset: The kernel doesn't support reset from sysfs for PCI device 0000:00:1f.6
2021-12-02 15:02:01.618+0000: libxl: libxl_pci.c:1520:do_pci_remove: xc_physdev_unmap_pirq irq=16: Invalid argument
2021-12-02 15:02:06.070+0000: libxl: libxl_device.c:983:libxl__initiate_device_generic_remove: backend /local/domain/69/backend/vif/15/0 already removed, cleanup frontend only
2021-12-02 15:02:09.949+0000: libxl: libxl_pci.c:1202:libxl__device_pci_reset: The kernel doesn't support reset from sysfs for PCI device 0000:00:1f.6
2021-12-02 15:03:18.465+0000: libxl: libxl_pci.c:1195:libxl__device_pci_reset: write to /sys/bus/pci/devices/0000:00:14.3/reset returned -1: Inappropriate ioctl for device
2021-12-02 15:04:18.633+0000: libxl: libxl_exec.c:226:libxl__xenstore_child_wait_deprecated: Device Model not ready
2021-12-02 15:04:18.633+0000: libxl: libxl_pci.c:1016:qemu_pci_add_xenstore: qemu refused to add device: 0000:00:14.3,msitranslate=0,power_mgmt=0
2021-12-02 15:04:18.633+0000: libxl: libxl_pci.c:1364:libxl__add_pcidevs: libxl_device_pci_add failed: -3
2021-12-02 15:04:18.633+0000: libxl: libxl_create.c:1517:domcreate_attach_devices: unable to add pci devices
2021-12-02 15:04:18.635+0000: libxl: libxl_pci.c:1202:libxl__device_pci_reset: The kernel doesn't support reset from sysfs for PCI device 0000:00:1f.6
2021-12-02 15:04:18.757+0000: libxl: libxl_pci.c:1520:do_pci_remove: xc_physdev_unmap_pirq irq=16: Invalid argument
2021-12-02 15:05:29.476+0000: libxl: libxl_pci.c:1195:libxl__device_pci_reset: write to /sys/bus/pci/devices/0000:00:14.3/reset returned -1: Inappropriate ioctl for device
2021-12-02 15:05:39.515+0000: libxl: libxl_device.c:1391:libxl__wait_for_backend: Backend /local/domain/0/backend/pci/164/0 not ready
2021-12-02 15:05:49.534+0000: libxl: libxl_device.c:1099:device_backend_callback: unable to remove device with path /local/domain/0/backend/vbd/164/51712
2021-12-02 15:05:49.562+0000: libxl: libxl_device.c:1099:device_backend_callback: unable to remove device with path /local/domain/0/backend/vbd/164/51728
2021-12-02 15:05:49.593+0000: libxl: libxl_device.c:1099:device_backend_callback: unable to remove device with path /local/domain/0/backend/vbd/164/51744
2021-12-02 15:05:49.627+0000: libxl: libxl_device.c:1099:device_backend_callback: unable to remove device with path /local/domain/0/backend/vbd/164/51760
2021-12-02 15:05:49.662+0000: libxl: libxl_device.c:1099:device_backend_callback: unable to remove device with path /local/domain/0/backend/pci/164/0
2021-12-02 15:05:49.685+0000: libxl: libxl.c:1669:devices_destroy_cb: libxl__devices_destroy failed for 164
2021-12-02 15:05:49.716+0000: libxl: libxl_device.c:1099:device_backend_callback: unable to remove device with path /local/domain/0/backend/vbd/163/51712
2021-12-02 15:05:49.740+0000: libxl: libxl_device.c:1099:device_backend_callback: unable to remove device with path /local/domain/0/backend/vbd/163/51728
2021-12-02 15:05:49.766+0000: libxl: libxl_device.c:1099:device_backend_callback: unable to remove device with path /local/domain/0/backend/vbd/163/51744
2021-12-02 15:05:49.795+0000: libxl: libxl_device.c:1099:device_backend_callback: unable to remove device with path /local/domain/0/backend/vbd/163/51760
2021-12-02 15:05:49.825+0000: libxl: libxl.c:1669:devices_destroy_cb: libxl__devices_destroy failed for 163
2021-12-02 15:06:35.170+0000: libxl: libxl_device.c:1099:device_backend_callback: unable to add device with path /local/domain/0/backend/vbd/165/51712
2021-12-02 15:06:35.233+0000: libxl: libxl_device.c:1099:device_backend_callback: unable to add device with path /local/domain/0/backend/vbd/165/51728
2021-12-02 15:06:35.321+0000: libxl: libxl_device.c:1099:device_backend_callback: unable to add device with path /local/domain/0/backend/vbd/165/51744
2021-12-02 15:06:35.457+0000: libxl: libxl_device.c:1099:device_backend_callback: unable to add device with path /local/domain/0/backend/vbd/165/51760
2021-12-02 15:06:35.457+0000: libxl: libxl_create.c:1320:domcreate_launch_dm: unable to add disk devices
2021-12-02 15:06:45.474+0000: libxl: libxl_device.c:1099:device_backend_callback: unable to remove device with path /local/domain/0/backend/vbd/165/51712
2021-12-02 15:06:45.492+0000: libxl: libxl_device.c:1099:device_backend_callback: unable to remove device with path /local/domain/0/backend/vbd/165/51728
2021-12-02 15:06:45.510+0000: libxl: libxl_device.c:1099:device_backend_callback: unable to remove device with path /local/domain/0/backend/vbd/165/51744
2021-12-02 15:06:45.532+0000: libxl: libxl_device.c:1099:device_backend_callback: unable to remove device with path /local/domain/0/backend/vbd/165/51760
2021-12-02 15:06:45.558+0000: libxl: libxl.c:1669:devices_destroy_cb: libxl__devices_destroy failed for 165

```

**Comment by conorsch** [comment]
@rocodes Did this error occur during the update run that switched your sys-* VMs to fedora-34? It looks very similar to https://github.com/freedomofpress/securedrop-workstation/issues/648, which I encountered during f31 -> f32, on similar hardware. 

Have you changed any BIOS settings recently? Disabling some devices that there were enabled at install-time can cause trouble with the PCI attachments. 

Finally, what happens when you reboot? Still stuck?

**Comment by rocodes** [comment]
- No, I switched the vms to Fedora-34 several weeks ago and run updates daily, so that's not the culprit
- Nope, haven't changed any BIOS settings recently
- Rebooting solves the issue, but the issue crops up again at the next update (I'm not sure if it's 100% of the time, I'll pay more attention, but it's at least 2-3 of the last 3-5 updater runs)

**Comment by rocodes** [comment]
Ok, `no-strict-reset` on both PCI devices (Network controller as well) resolves this, should have rtfm'd. Closing.
