### ISSUE TITLE
test_all_sd_vm_apt_sources (test_vms_platform.SD_VM_Platform_Tests.test_all_sd_vm_apt_sources) CI failure

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop-workstation#982]
https://ws-ci-runner.securedrop.org/2024-04-11-235217913151-3ce1c0ad0f697cbaa0ff62b554c81eed2b04e079-Qubes_4.2_A-base_setup_20240410.log.txt

```
INFO:[2024-04-12-00:31:48:674953] ======================================================================
INFO:[2024-04-12-00:31:48:674984] FAIL: test_all_sd_vm_apt_sources (test_vms_platform.SD_VM_Platform_Tests.test_all_sd_vm_apt_sources)
INFO:[2024-04-12-00:31:48:675022] Test all VMs fpf apt source list iteratively.
INFO:[2024-04-12-00:31:48:675056] ----------------------------------------------------------------------
INFO:[2024-04-12-00:31:48:675096] Traceback (most recent call last):
INFO:[2024-04-12-00:31:48:675130]   File "/home/user/securedrop-workstation/tests/test_vms_platform.py", line 224, in test_all_sd_vm_apt_sources
INFO:[2024-04-12-00:31:48:675161]     self._validate_apt_sources(vm)
INFO:[2024-04-12-00:31:48:675196]   File "/home/user/securedrop-workstation/tests/test_vms_platform.py", line 83, in _validate_apt_sources
INFO:[2024-04-12-00:31:48:675230]     self.assertIn(self.apt_url, contents, f"{vm.name} missing apt sources list")
INFO:[2024-04-12-00:31:48:675261] AssertionError: 'deb [arch=amd64] https://apt-test.freedom.press bookworm nightlies' not found in 'deb [arch=amd64] https://apt-test.freedom.press bookworm main nightlies' : sd-gpg missing apt sources list
```

**Comment by legoktm** [comment]
Test is flaky now, it's sometimes failing as:
```
INFO:[2024-04-19-19:30:26:991078] ======================================================================
INFO:[2024-04-19-19:30:26:991283] FAIL: test_all_sd_vm_apt_sources (test_vms_platform.SD_VM_Platform_Tests.test_all_sd_vm_apt_sources)
INFO:[2024-04-19-19:30:26:991333] Test all VMs fpf apt source list iteratively.
INFO:[2024-04-19-19:30:26:991376] ----------------------------------------------------------------------
INFO:[2024-04-19-19:30:26:991416] Traceback (most recent call last):
INFO:[2024-04-19-19:30:26:991454]   File "/home/user/securedrop-workstation/tests/test_vms_platform.py", line 224, in test_all_sd_vm_apt_sources
INFO:[2024-04-19-19:30:26:991493]     self._validate_apt_sources(vm)
INFO:[2024-04-19-19:30:26:991530]   File "/home/user/securedrop-workstation/tests/test_vms_platform.py", line 83, in _validate_apt_sources
INFO:[2024-04-19-19:30:26:991568]     self.assertEqual(expected, contents, f"{vm.name} missing apt sources list")
INFO:[2024-04-19-19:30:26:991605] AssertionError: 'deb [arch=amd64] https://apt-test.freedom.press bookworm main nightlies' != 'deb [arch=amd64] https://apt-test.freedom.press bookworm nightlies main'
INFO:[2024-04-19-19:30:26:991644] - deb [arch=amd64] https://apt-test.freedom.press bookworm main nightlies
INFO:[2024-04-19-19:30:26:991680] ?                                                         -----
INFO:[2024-04-19-19:30:26:991716] + deb [arch=amd64] https://apt-test.freedom.press bookworm nightlies main
INFO:[2024-04-19-19:30:26:991752] ?                                                                   +++++
INFO:[2024-04-19-19:30:26:991787]  : sd-gpg missing apt sources list
```

Seems like salt reorders components in a non-deterministic way.
